#command_file: null
#commands: null
#compute_environment: LOCAL_MACHINE
#deepspeed_config:
#  #deepspeed_config_file: accelerate_cfgs/zero_stage_3_config.json
#  deepspeed_config_file: accelerate_cfgs/zero_stage_2_config.json
#  #zero3_init_flag: true
#  zero3_init_flag: false
#distributed_type: DEEPSPEED
#downcast_bf16: 'no'
#dynamo_config:
#  dynamo_backend: INDUCTOR
#fsdp_config: {}
#gpu_ids: null
#machine_rank: 0
#main_process_ip: null
#main_process_port: null
#main_training_function: main
#megatron_lm_config: {}
#num_machines: 1
#num_processes: 4
#rdzv_backend: static
#same_network: true
#tpu_name: null
#tpu_zone: null
#use_cpu: false

# compute_environment: LOCAL_MACHINE
# debug: false
# deepspeed_config:
#   deepspeed_config_file: accelerate_cfgs/zero3.json
#   zero3_init_flag: true
# distributed_type: DEEPSPEED
# downcast_bf16: 'no'
# machine_rank: 0
# main_training_function: main
# num_machines: 1
# num_processes: 8
# rdzv_backend: static
# same_network: true
# tpu_env: []
# tpu_use_cluster: false
# tpu_use_sudo: false
# use_cpu: false

compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
  stage3_gather_16bit_weights_on_model_save: true
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false